DROP TABLE IF EXISTS NBA;
CREATE TABLE NBA (p1 float, p2 float, p3 float, p4 float, p5 float, p6 float, p7 float, p8 float, p1_v float);
COPY NBA (p1, p2, p3, p4, p5, p6, p7, p8, p1_v) FROM 'nba-U-8-17264.csv' DELIMITERS ',' CSV QUOTE '''';
alter table NBA add p2_v float;
alter table NBA add p3_v float;
alter table NBA add p4_v float;
alter table NBA add p5_v float;
alter table NBA add p6_v float;
alter table NBA add p7_v float;
alter table NBA add p8_v float;
update NBA set p1_v = random(),p2_v = random(),p3_v = random(),p4_v = random(),p5_v = random(),p6_v = random(),p7_v = random(),p8_v = random();

DROP TABLE IF EXISTS HOUSE;
CREATE TABLE HOUSE (p1 float, p2 float, p3 float, p4 float, p5 float, p6 float, p1_v float);
COPY HOUSE (p1, p2, p3, p4, p5, p6, p1_v) FROM 'house-U-6-127931.csv' DELIMITERS ',' CSV QUOTE '''';
alter table HOUSE add p2_v float;
alter table HOUSE add p3_v float;
alter table HOUSE add p4_v float;
alter table HOUSE add p5_v float;
alter table HOUSE add p6_v float;
update HOUSE set p1_v = random(),p2_v = random(),p3_v = random(),p4_v = random(),p5_v = random(),p6_v = random();

DROP TABLE IF EXISTS WEATHER;
CREATE TABLE WEATHER (p1 float, p2 float, p3 float, p4 float, p5 float, p6 float, p7 float, p8 float, p9 float, p10 float, p11 float, p12 float, p13 float, p14 float, p15 float, p1_v float);
COPY WEATHER (p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p1_v) FROM 'elv_weather-U-15-566268.csv' DELIMITERS ',' CSV QUOTE '''';
alter table WEATHER add p2_v float;
alter table WEATHER add p3_v float;
alter table WEATHER add p4_v float;
alter table WEATHER add p5_v float;
alter table WEATHER add p6_v float;
alter table WEATHER add p7_v float;
alter table WEATHER add p8_v float;
alter table WEATHER add p9_v float;
alter table WEATHER add p10_v float;
alter table WEATHER add p11_v float;
alter table WEATHER add p12_v float;
alter table WEATHER add p13_v float;
alter table WEATHER add p14_v float;
alter table WEATHER add p15_v float;
update WEATHER set p1_v = random(),p2_v = random(),p3_v = random(),p4_v = random(),p5_v = random(),p6_v = random(),p7_v = random(),p8_v = random(),p9_v = random(),p10_v = random(),p11_v = random(),p12_v = random(),p13_v = random(),p14_v = random(),p15_v = random();